[project]
name = "discrete-borrowing-computer"
authors = ["Web3 Lending Team"]
description = "A decentralized smart contract for secure and transparent financial borrowing transactions"
telemetry = false
requirements = []
[contracts.discrete-borrowing-computer]
path = "contracts/discrete-borrowing-computer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
